apiVersion: v1
kind: ServiceAccount
metadata:
  name: example-sa 
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: example-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: example-RoleBinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: example-sa 
    namespace: default
roleRef:
  kind: Role
  name: example-role
  apiGroup: rbac.authorization.k8s.io

---

#role--> rolebinding-->  serviceaccout--> deployment-->pod-->app