# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: example-app

---
# Service Account for frontend
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: example-app

---
# Role: allows reading ConfigMaps in namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: configmap-reader
  namespace: example-app
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]

---
# RoleBinding for frontend ServiceAccount
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-config-reader
  namespace: example-app
subjects:
  - kind: ServiceAccount
    name: frontend-sa
    namespace: example-app
roleRef:
  kind: Role
  name: configmap-reader
  apiGroup: rbac.authorization.k8s.io

---
# Service Account for monitoring (needed for ClusterRoleBinding)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring-sa
  namespace: kube-system

---
# ClusterRole: read pods & nodes
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-reader
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes"]
    verbs: ["get", "list", "watch"]

---
# ClusterRoleBinding for monitoring SA
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monitoring-bind
subjects:
  - kind: ServiceAccount
    name: monitoring-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
